# Generated by Django 5.2.16 on 2026-08-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdgenerator", "0002_githubrun_github_run_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=100, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "filename",
                    models.CharField(blank=True, default="rustdesk", max_length=200),
                ),
                ("engine", models.CharField(default="docker", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuildJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=30)),
                ("uuid", models.CharField(db_index=True, max_length=100)),
                (
                    "filename",
                    models.CharField(blank=True, default="rustdesk", max_length=200),
                ),
                ("status", models.CharField(default="queued", max_length=100)),
                ("log_url", models.CharField(blank=True, default="", max_length=500)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("position", models.IntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="rdgenerator.buildbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
