# Generated by Django 5.2.16 on 2026-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdgenerator", "0003_buildbatch_buildjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrun",
            name="local",
            field=models.BooleanField(default=False),
        ),
    ]
